package day26_LocalTime_varargs;

public class C08_Varargs {
    public static void main(String[] args) {
  /*
  - JAVA DA BIR METHOD PARAMETRELERINE UYGUN ARGUMENTE SAHIP METHOD CALL OLDUGUNDA CALISIR.

  ORNEGIN: 2 INT PARAMETRE VARSA SADECE 2 INT ARGUMENT ILE METHOD CALL YAPILDIGINDA CALISIR.

  - JAVA AYNI DATA TURUNE SAHIP OLMAK SARTIYLA PARAMETRE SAYISINI ESNEK TUTABILMEK ICIN VARARGS OLUSTURMUSTUR.

  - VARARGS BIR ARRAY'DIR. BIZ ARGUMENT OLARAK BURAYA NE YAZARSAK ONU BIR ARRAY OLARAK KAYDEDER.
  METHODDA ARRAY ELEMENTLERINI


  - VARARGS COGUNLUKLA BIR METHODDA KULLANILIR. BUNUNDA SEBEBI ARRAY ALT YAPISINI KULLANIYOR OLMASI.

  - VARARGS ICIN 3 NOKTA KULLANILIR.
  PUBLIC STATIC VOID TOPLA(INT A ...)

   */


    }
}
